### ISSUE TITLE
Error on Loading (looks like the old/closed bug that was not resolved)

### ISSUE THREAD

**Issue by Brianckramer** [custom-components/sensor.weatheralerts#12]
Using newest version (downloaded 1/20/2019).  It is in the proper folder, and this is not my first/only custom component.

**Describe the bug**
Fails to load.  My config:

```
- platform: weatheralerts
  sameid: '029189'
```

**log**
Sun Jan 20 2019 20:40:51 GMT-0600 (Central Standard Time)

Error while setting up platform weatheralerts
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/weatheralerts.py", line 38, in setup_platform
    add_devices([WeatherAlertsSensor(sameid)])
  File "/config/custom_components/sensor/weatheralerts.py", line 43, in __init__
    self.update()
  File "/config/custom_components/sensor/weatheralerts.py", line 47, in update
    nws = WeatherAlerts(samecodes=self._sameid)
  File "/config/deps/lib/python3.6/site-packages/weatheralerts/weather_alerts.py", line 43, in __init__
    self.scope = self.geo.getfeedscope(self.samecodes)
  File "/config/deps/lib/python3.6/site-packages/weatheralerts/geo.py", line 59, in getfeedscope
    states = self._get_states_from_samecodes(geocodes)
  File "/config/deps/lib/python3.6/site-packages/weatheralerts/geo.py", line 75, in _get_states_from_samecodes
    state = self.samecodes[code]['state']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ludeeus** [comment]
if it fails to load just try it again.
I tested with your sameid now, and got `'Wind Chill Warning'`

**Comment by chipriley** [comment]
I'm getting this also. Config and install location is correct. I have rebooted/restarted multiple times and it has never worked. 

`2019-02-25 15:03:40 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform weatheralerts
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/weatheralerts/sensor.py", line 39, in setup_platform
    add_devices([WeatherAlertsSensor(sameid)])
  File "/config/custom_components/weatheralerts/sensor.py", line 44, in __init__
    self.update()
  File "/config/custom_components/weatheralerts/sensor.py", line 48, in update
    nws = WeatherAlerts(samecodes=self._sameid)
  File "/config/deps/lib/python3.7/site-packages/weatheralerts/weather_alerts.py", line 43, in __init__
    self.scope = self.geo.getfeedscope(self.samecodes)
  File "/config/deps/lib/python3.7/site-packages/weatheralerts/geo.py", line 59, in getfeedscope
    states = self._get_states_from_samecodes(geocodes)
  File "/config/deps/lib/python3.7/site-packages/weatheralerts/geo.py", line 75, in _get_states_from_samecodes
    state = self.samecodes[code]['state']
TypeError: 'NoneType' object is not subscriptable `

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johntdyer** [comment]
Same here... 

```

**Comment by ludeeus** [comment]
`0.1.1` _should_ fix that.
