### ISSUE TITLE
Error with new update. sameid: '021001'

### ISSUE THREAD

**Issue by rotcop4u2** [custom-components/sensor.weatheralerts#8]
2018-09-13 02:23:06 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform weatheralerts
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/weatheralerts.py", line 38, in setup_platform
    add_devices([WeatherAlertsSensor(sameid)])
  File "/home/homeassistant/.homeassistant/custom_components/sensor/weatheralerts.py", line 43, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/sensor/weatheralerts.py", line 48, in update
    self._published = nws.alerts[0].published
IndexError: list index out of range

**Comment by rotcop4u2** [comment]
the issue was with the "sameid" i guess it was invalid. tried another 3rd time was a charm.
